In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
#Contents:
    #1 Data Processing: read file, 
                       #deal missing value, 
                       #transform categorial(Create Dummy variable) columns independent vs. dependnent variables
                       #splitting the dataset into the training and. test sets.
                       #Feature Scaling(Import! Always apply the feature scaling after the splitting because test dataset should be brand new not leaking the mean,max or min from the train dataset)
                        #chose between standardisation(applies to all kinds) or normorlisation(apply when fits normalization distribution)
     

In [4]:
dataset=pd.read_csv("/Users/lipingsun/Desktop/wcpa/Python/ML/Machine Learning A-Z (Codes and Datasets)/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Python/Data.csv")
x=dataset.iloc[:, :-1].values #iloc means index of columns and columns, : means all rows,-1 means the excluding the last column. 
y=dataset.iloc[:, -1].values  #iloc all rows and the last columns as dependent variable.

In [5]:
print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [6]:
#Taking Care of Missing Data
#use imputer as an object of SimpleImputer, with a strategy of MEAN(median, mode etc)
#call the method fit to locate the missing value
#replace the missing value by filling up with the strategy called.
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3]) #For large dataset, apply fit to all numeric columns, not string columns.
x[:,1:3]=imputer.transform(x[:,1:3])

In [7]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [8]:
#Encoding categorical data: Dummy variable
#1 Independent Variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [9]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [10]:
#Encoding categorical data
#1 dependent Binary Variable
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [11]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [13]:
print(x_train)
print(y_train)
print(x_test)
print(y_test)


[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[0 1 0 0 1 1 0 1]
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1]


In [14]:
#Feature Scaling: Normalization vs. Standardization(Preferred).(Some features are dominant than others because of different scaling)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
#do we apply scaler to the dumming variable? NO! They already are(0, 1). Only numerical variable.
x_train[:,3:] =sc.fit_transform(x_train[:,3:]) #fit_transform will do: FIT find the mean and standard deviation, TRANSFORM will apply the formula of standardization to scale it.
x_test[:,3:]=sc.transform(x_test[:,3:])#because the test dataset is new dataset with no mean, so apply the test dataset's mean and standardization to scale it to the training model to predict based on same scale.



In [15]:
print(x_train)


[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [16]:
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
